version: "3.8"
services:
  #User-Service
  user-profile-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yotpo-orders-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_container:5432/postgres
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
    links:
      - db
    ports:
      - '8080:8080'
    depends_on:
      - db
  #Postgres
  db:
    image: postgres:15
    container_name: yotpo-orders-postgres
    restart: always
    environment:
      - POSTGRES_DB=yotpo-orders
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres-db-data:/var/lib/postgres/data